import LegalLayout from './LegalLayout';

export default function DisclaimerPage() {
  return (
    <LegalLayout title="Disclaimer" lastUpdated="2026-05-21">
      <p>
        ChefFlow is a productivity tool for professional kitchens. Please read this disclaimer
        carefully. By using ChefFlow you acknowledge and accept the limitations described below.
      </p>

      <h2 id="no-warranty" className="text-xl md:text-2xl font-semibold">No warranty</h2>
      <p>
        ChefFlow is provided "as is" and "as available" without warranty of any kind, express or
        implied. To the fullest extent permitted by UK law we exclude all implied warranties,
        including merchantability, fitness for a particular purpose, and non-infringement. We do not
        warrant that the platform will be uninterrupted, error-free, or free from harmful components.
      </p>

      <h2 id="food-safety" className="text-xl md:text-2xl font-semibold">Food safety and professional responsibility</h2>
      <p>
        Nothing in ChefFlow constitutes food-safety advice, HACCP guidance, or a validated Standard
        Operating Procedure (SOP). All content — whether created by you, generated by the AI, or
        drawn from the community recipe library — is informational only.
      </p>
      <p>
        You remain solely responsible for the safety of every dish you prepare and serve. That
        responsibility includes, but is not limited to: verifying cooking times and temperatures
        against your kitchen's equipment, complying with your local authority's environmental health
        requirements, maintaining your team's food hygiene training (Level 2 / Level 3 or
        equivalent), and operating a documented HACCP system appropriate to your food business.
      </p>
      <p>
        ChefFlow does not account for your specific kitchen layout, equipment calibration, team
        competency, or the regulatory conditions of your business. Do not substitute any output from
        this platform for the judgment of a qualified, experienced chef.
      </p>

      <h2 id="allergens" className="text-xl md:text-2xl font-semibold">Allergen information — important notice</h2>
      <p>
        ChefFlow includes allergen-tagging features that attempt to identify the 14 major allergens
        regulated under UK law (the "UK-14") based on ingredient names and AI inference.{' '}
        <strong>
          This allergen tagging is best-effort and is not a certified allergen analysis.
        </strong>{' '}
        It cannot account for cross-contamination, supplier reformulations, or undeclared allergens
        in branded ingredients.
      </p>
      <p>
        You must not rely on ChefFlow's allergen tags as the sole basis for allergen disclosure to
        guests or customers. Before serving any dish, you must:
      </p>
      <ul>
        <li>Check every ingredient label and your supplier's allergen declarations directly.</li>
        <li>
          Assess cross-contamination risk in your kitchen and supply chain.
        </li>
        <li>
          Provide accurate written or verbal allergen information to customers as required by the
          Food Information Regulations 2014 and, where applicable, the rules introduced by Natasha's
          Law (PPDS regulations effective October 2021). [REVIEW: confirm current FSA guidance applies
          to your food business category and whether any exemptions or additional obligations apply
          to your specific operation — e.g., distance selling, caterers, supper clubs.]
        </li>
      </ul>
      <p>
        Where in doubt, consult a qualified allergen advisor or the Food Standards Agency (FSA)
        guidance at <a href="https://www.food.gov.uk/business-guidance/allergen-guidance-for-food-businesses" target="_blank" rel="noreferrer">food.gov.uk</a>.
        ChefFlow accepts no liability for allergen-related harm arising from reliance on
        platform-generated allergen information.
      </p>

      <h2 id="ai-content" className="text-xl md:text-2xl font-semibold">AI-generated content</h2>
      <p>
        ChefFlow's AI Co-Chef feature generates recipe drafts, menu suggestions, prep workflows, and
        event plans using a large-language model (LLM). LLMs can produce plausible-sounding but
        incorrect output. Specifically:
      </p>
      <ul>
        <li>
          <strong>Quantities and ratios</strong> may be wrong. Verify every recipe against
          established reference sources before use in a professional context.
        </li>
        <li>
          <strong>Techniques and temperatures</strong> may not meet food-safety requirements or suit
          your equipment. Cross-check against accredited culinary or food-safety references.
        </li>
        <li>
          <strong>Allergen identification</strong> within AI output is an estimate only (see the
          Allergen section above).
        </li>
        <li>
          <strong>Timing and sequencing</strong> in AI-generated workflows may be impractical for
          your team size or kitchen configuration.
        </li>
      </ul>
      <p>
        Treat all AI-generated content as a starting point, not a finished product. A competent
        senior team member must review and approve any AI-generated workflow or recipe before it is
        used in a live service.
      </p>

      <h2 id="community-content" className="text-xl md:text-2xl font-semibold">Community recipe content</h2>
      <p>
        Recipes published by other chefs to ChefFlow's community library have not been reviewed,
        tested, or verified by ChefFlow. We make no representations about their accuracy, safety, or
        suitability for your operation. Apply the same professional scrutiny to community recipes
        that you would to any untested recipe from an external source.
      </p>

      <h2 id="liability-cap" className="text-xl md:text-2xl font-semibold">Limitation of liability</h2>
      <p>
        To the fullest extent permitted by applicable UK law, ChefFlow's total aggregate liability to
        you arising out of or in connection with the platform — whether in contract, tort (including
        negligence), breach of statutory duty, or otherwise — is limited to the fees you paid to
        ChefFlow in the twelve months preceding the event giving rise to the claim, or £100 (one
        hundred pounds sterling), whichever is greater. [REVIEW: confirm this cap is enforceable for
        your business structure and that it is appropriately qualified to exclude death, personal
        injury, and fraud per s.2(1) Unfair Contract Terms Act 1977 and CRA 2015.]
      </p>
      <p>
        Nothing in this disclaimer excludes or limits ChefFlow's liability for death or personal
        injury caused by negligence, fraud or fraudulent misrepresentation, or any other liability
        that cannot lawfully be excluded or limited under UK law.
      </p>

      <h2 id="contact" className="text-xl md:text-2xl font-semibold">Contact</h2>
      <p>
        Questions about this disclaimer: <a href="mailto:chefflow.support@[REVIEW domain]">chefflow.support@[REVIEW domain]</a>. [REVIEW: insert the verified support email address before public launch.]
      </p>

      <p>
        <em>
          This is a draft document prepared for solicitor review. It is not finalized legal advice.
          A UK-qualified solicitor should red-line this document before it is published. Search for
          [REVIEW] to find items requiring specific legal or business input.
        </em>
      </p>
    </LegalLayout>
  );
}
