import LegalLayout from './LegalLayout';

export default function TermsPage() {
  return (
    <LegalLayout title="Terms &amp; Conditions" lastUpdated="2026-05-19">
      <h2>1. Acceptance</h2>
      <p>
        By accessing or using ChefFlow you agree to these Terms. If you are using ChefFlow on
        behalf of a food business, you confirm you have authority to bind that business. We may
        update these Terms and will show a new "last updated" date when we do — continued use after
        that date constitutes acceptance.
      </p>

      <h2>2. Scope of service</h2>
      <p>
        ChefFlow is a recipe and event-management tool designed to support professional kitchens. It
        is provided as a productivity aid only. ChefFlow makes no warranty of fitness for any
        specific commercial food-service purpose, regulatory compliance, or food-safety outcome.
      </p>

      <h2>3. Intellectual property</h2>
      <p>
        You retain full ownership of all recipes, event data, and other content you create in
        ChefFlow. By using the AI features you grant ChefFlow (and its LLM processor, Groq) a
        limited, transient licence to process that content solely to return the requested output.
        ChefFlow retains ownership of the software, user interface, and all LLM prompt scaffolding.
        You may not reverse-engineer or copy the software.
      </p>

      <h2>4. LLM-generated content and allergen liability</h2>
      <p>
        AI-generated recipes, workflows, and allergen detections are estimates produced by a
        large-language model. They may contain errors. ChefFlow's allergen detection is
        LLM-estimated and informational. Always verify allergens against your own sourcing before
        serving. The platform is a tool — operational food-safety responsibility remains with the
        regulated food business.
      </p>
      <p>
        You must not serve any dish or follow any workflow generated by ChefFlow without independent
        professional verification, including allergen checks with ingredient suppliers.
      </p>

      <h2>5. Account termination</h2>
      <p>
        We may suspend or terminate your account for misuse, violation of these Terms, or
        non-payment if a paid tier is introduced. On termination, your auth credentials are removed
        from Clerk. Your recipes, events, and workflows stored in your browser's IndexedDB remain on
        your device until you clear site data — we have no ability to delete them remotely.
      </p>

      <h2>6. Third-party processors</h2>
      <p>ChefFlow uses the following third-party services:</p>
      <ul>
        <li><strong>Clerk</strong> — authentication. <a href="https://clerk.com/legal/privacy" target="_blank" rel="noreferrer">Clerk Privacy Policy</a></li>
        <li><strong>Groq</strong> — LLM inference for recipe, workflow, and menu features. <a href="https://groq.com/privacy-policy/" target="_blank" rel="noreferrer">Groq Privacy Policy</a></li>
        <li><strong>Google</strong> — Maps Places autocomplete for event locations. <a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">Google Privacy Policy</a></li>
        <li><strong>Cloudflare</strong> — hosting, Workers, and KV storage. <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noreferrer">Cloudflare Privacy Policy</a></li>
      </ul>

      <h2>7. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, ChefFlow's total liability to you in any
        twelve-month period is capped at fees you paid to ChefFlow in that period. ChefFlow is not
        liable for any indirect, consequential, or economic loss, including loss arising from
        reliance on AI-generated content or allergen information.
      </p>

      <h2>8. Governing law</h2>
      <p>
        These Terms are governed by the law of England and Wales. You agree to submit to the
        exclusive jurisdiction of the English courts.
      </p>

      <p><em>This document is a plain-English summary, not legal advice. Have a UK-qualified solicitor review before public launch.</em></p>
    </LegalLayout>
  );
}
