/**
 * E2E spec: SettingsPage — Profile section
 *
 * CLERK GATING:
 * Runs with VITE_E2E_MODE=true (set in playwright.config.ts webServer env).
 * Routes render via <UngatedApp>; no live Clerk account required.
 *
 * PERSISTENCE:
 * useProfileStore persists to localStorage under "chefflow:profile:v1"
 * (Zustand persist middleware). The spec verifies that values survive a full
 * page reload — the canonical persistence test for a localStorage-backed store.
 *
 * PHOTO UPLOAD:
 * page.setInputFiles() with { name, mimeType, buffer } delivers a synthetic
 * 1×1 JPEG to the hidden file input without needing a file on disk.
 * downscaleToDataUrl() uses canvas which jsdom does not support, but Playwright
 * runs in a real Chromium browser where canvas works.
 *
 * NAVIGATION:
 * The spec confirms the Settings gear icon in TopNav/MobileTopBar navigates to
 * /settings. Viewport is forced wide (1280×720) so TopNav is visible.
 */

import { test, expect, type Page } from '@playwright/test';

// Minimal valid 1×1 PNG in base64 (69 bytes — generated by Python's zlib/struct).
// Using PNG rather than JPEG because the PNG binary format is precisely specified
// and trivial to synthesise. downscaleToDataUrl() still converts it to JPEG via
// canvas.toDataURL('image/jpeg'), so the saved data URL is a JPEG.
const TINY_PNG_B64 =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGP4z8AAAAMB' +
  'AQDJ/pLvAAAAAElFTkSuQmCC';

/**
 * Clear IDB stores, seed flags, and the profile store so each test is isolated.
 */
async function resetAppState(page: Page) {
  await page.evaluate(() => {
    return new Promise<void>((resolve, reject) => {
      const req = indexedDB.open('chefflow');
      req.onsuccess = () => {
        const db = req.result;
        const storeNames = Array.from(db.objectStoreNames) as string[];
        if (storeNames.length === 0) { db.close(); resolve(); return; }
        const tx = db.transaction(storeNames, 'readwrite');
        let pending = storeNames.length;
        for (const name of storeNames) {
          const clearReq = tx.objectStore(name).clear();
          clearReq.onsuccess = () => { if (--pending === 0) { db.close(); resolve(); } };
          clearReq.onerror = () => { db.close(); reject(clearReq.error); };
        }
        tx.onerror = () => { db.close(); reject(tx.error); };
      };
      req.onerror = () => reject(req.error);
      req.onupgradeneeded = () => { req.result.close(); resolve(); };
    });
  });
  await page.evaluate(() => {
    localStorage.removeItem('chefflow:seeded-demo-v3');
    localStorage.removeItem('chefflow:seeded-demo-events-v4');
    localStorage.removeItem('chefflow:profile:v1');
    sessionStorage.removeItem('chefflow:event-review-draft');
  });
}

test.describe('SettingsPage — Profile section', () => {
  test.use({ viewport: { width: 1280, height: 720 } });

  test.beforeEach(async ({ page }) => {
    await page.goto('/');
    await resetAppState(page);
  });

  // ---------------------------------------------------------------------------
  test('gear icon in TopNav navigates to /settings', async ({ page }) => {
    await page.goto('/recipes');
    // Wait for TopNav to be visible (desktop viewport ensures TopNav renders)
    const settingsLink = page.getByRole('link', { name: /settings/i }).first();
    await expect(settingsLink).toBeVisible({ timeout: 10_000 });
    await settingsLink.click();
    await expect(page).toHaveURL(/\/settings/);
    await expect(page.getByRole('heading', { name: /settings/i })).toBeVisible();
  });

  // ---------------------------------------------------------------------------
  test('display name: type + blur → persists in localStorage and survives reload', async ({ page }) => {
    await page.goto('/settings');
    const nameInput = page.getByTestId('settings-profile-name-input');
    await expect(nameInput).toBeVisible({ timeout: 10_000 });

    // Type a name and blur to trigger the onBlur save
    await nameInput.fill('Gordon Ramsay');
    await nameInput.press('Tab');

    // Verify localStorage was written immediately
    const stored = await page.evaluate(() =>
      localStorage.getItem('chefflow:profile:v1'),
    );
    expect(stored).toContain('Gordon Ramsay');

    // Reload and confirm the value is rehydrated into the input
    await page.reload();
    const reloadedInput = page.getByTestId('settings-profile-name-input');
    await expect(reloadedInput).toHaveValue('Gordon Ramsay', { timeout: 10_000 });
  });

  // ---------------------------------------------------------------------------
  test('avatar: pick a photo → avatar img appears; clear → placeholder restored', async ({ page }) => {
    await page.goto('/settings');
    await expect(page.getByTestId('settings-profile-photo-pick')).toBeVisible({ timeout: 10_000 });

    // The hidden file input does not have a data-testid, but is the only
    // file input on the page. Use setInputFiles via its accept attribute.
    const fileInput = page.locator('input[type="file"][accept="image/*"]').first();

    await fileInput.setInputFiles({
      name: 'avatar.png',
      mimeType: 'image/png',
      buffer: Buffer.from(TINY_PNG_B64, 'base64'),
    });

    // Avatar img should appear once downscaleToDataUrl resolves
    const avatarImg = page.getByTestId('settings-profile-avatar-img');
    await expect(avatarImg).toBeVisible({ timeout: 10_000 });
    // src is a data URL — starts with data:image/jpeg
    const src = await avatarImg.getAttribute('src');
    expect(src).toMatch(/^data:image\/jpeg/);

    // Remove photo → img goes away, "Remove photo" button goes away
    await page.getByTestId('settings-profile-photo-clear').click();
    await expect(avatarImg).not.toBeVisible();
    await expect(page.getByTestId('settings-profile-photo-clear')).not.toBeVisible();
  });

  // ---------------------------------------------------------------------------
  test('avatar persists in localStorage and survives reload', async ({ page }) => {
    await page.goto('/settings');
    await expect(page.getByTestId('settings-profile-photo-pick')).toBeVisible({ timeout: 10_000 });

    const fileInput = page.locator('input[type="file"][accept="image/*"]').first();
    await fileInput.setInputFiles({
      name: 'avatar.png',
      mimeType: 'image/png',
      buffer: Buffer.from(TINY_PNG_B64, 'base64'),
    });

    await expect(page.getByTestId('settings-profile-avatar-img')).toBeVisible({ timeout: 10_000 });

    // Verify the data URL was persisted to localStorage
    const stored = await page.evaluate(() =>
      localStorage.getItem('chefflow:profile:v1'),
    );
    expect(stored).toContain('data:image/jpeg');

    // Reload — avatar should still be visible from persisted store
    await page.reload();
    await expect(page.getByTestId('settings-profile-avatar-img')).toBeVisible({ timeout: 10_000 });
  });
});
